### ISSUE TITLE
给imageView设置占位图的时候是否支持gif图片呢？

### ISSUE THREAD

**Issue by chd123456** [Silence-GitHub/BBWebImage#1]

**Comment by Silence-GitHub** [comment]
支持。用 BBAnimatedImageView 作为 imageView，用 gif 占位图的 Data 生成 BBAnimatedImage 作为占位图。如果多个地方用同一个占位图，BBAnimatedImage 可以只生成一次，然后复用。

然而，不建议用动图作为占位图。动图再怎么优化都比较占用资源。为了出现短暂时间的占位图消耗资源，不值得。
